manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.6.0
      clone-depth: 1
      import:
        name-blocklist:
          - hal_atmel
          - hal_altera
          - hal_ambiq
          - hal_altera
          - hal_cypress
          - hal_espressif
          - hal_ethos_u
          - hal_gigadevice
          - hal_infineon
          - hal_intel
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_renesas
          - hal_rpi_pico
          - hal_silabs
          - hal_xtensa
          - hal_st
          - hal_ti
          - hal_telink
          - hal_wurthelektronik
          - libmetal
          - loramac-node
          - hal_nuvoton
          - hal_quicklogic
          - hal_stm32
          - trusted-firmware-m
          - trusted-firmware-a
          - picolibc
          - hostap
          - liblc3
          - net-tools
          - mipi-sys-t
  self:
    path: app
